#!/usr/bin/env python3
"""
Lebanon Locals - Asset Bundler
Combines commonly used JavaScript and CSS files into bundles for faster loading.
Run this script before deploying to production.
"""

import os
import re
import sys
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).parent.parent
PUBLIC_DIR = BASE_DIR / 'public'
ASSETS_DIR = PUBLIC_DIR / 'assets'
JS_DIR = ASSETS_DIR / 'js'
CSS_DIR = ASSETS_DIR / 'css'
BUNDLES_DIR = ASSETS_DIR / 'bundles'

# Common JavaScript files (in load order)
COMMON_JS_FILES = [
    'config.js',
    'load-modals.js',
    'auth.js',
    'api.js',
    'wishlist.js',
    'notifications.js',
    'header.js',
    'load-header-standard.js',
    'load-footer.js'
]

# Common CSS files (in load order)
COMMON_CSS_FILES = [
    'variables.css',
    'auth.css'
]

def minify_js(content):
    """Basic JavaScript minification"""
    # Remove single-line comments (but preserve //! comments)
    content = re.sub(r'(?<!:)//(?![/!]).*?$', '', content, flags=re.MULTILINE)
    # Remove multi-line comments (but preserve /*! comments)
    content = re.sub(r'/\*(?!!)[^*]*\*+(?:[^/*][^*]*\*+)*/', '', content)
    # Remove extra whitespace
    content = re.sub(r'\n\s*\n', '\n', content)
    # Remove leading/trailing whitespace from lines
    lines = [line.strip() for line in content.split('\n')]
    content = '\n'.join(line for line in lines if line)
    return content

def minify_css(content):
    """Basic CSS minification"""
    # Remove comments
    content = re.sub(r'/\*[^*]*\*+(?:[^/*][^*]*\*+)*/', '', content)
    # Remove extra whitespace
    content = re.sub(r'\s+', ' ', content)
    content = re.sub(r'\s*{\s*', '{', content)
    content = re.sub(r'\s*}\s*', '}', content)
    content = re.sub(r'\s*:\s*', ':', content)
    content = re.sub(r'\s*;\s*', ';', content)
    content = re.sub(r'\s*,\s*', ',', content)
    return content.strip()

def bundle_files(file_list, source_dir, output_file, minify_func=None):
    """Bundle multiple files into one"""
    bundled_content = []
    bundled_content.append(f'/* Bundled: {", ".join(file_list)} */\n')
    bundled_content.append(f'/* Generated by bundle-assets.py */\n\n')
    
    for filename in file_list:
        file_path = source_dir / filename
        if not file_path.exists():
            print(f'Warning: {filename} not found, skipping...')
            continue
        
        print(f'Bundling {filename}...')
        content = file_path.read_text(encoding='utf-8')
        
        # Add file separator comment
        bundled_content.append(f'\n/* ===== {filename} ===== */\n')
        
        if minify_func:
            content = minify_func(content)
        
        bundled_content.append(content)
        bundled_content.append('\n')
    
    # Write bundled file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(''.join(bundled_content), encoding='utf-8')
    size_kb = output_file.stat().st_size / 1024
    print(f'Created {output_file.name} ({size_kb:.1f} KB)')

def main():
    """Main bundling function"""
    print('Starting asset bundling...\n')
    
    # Create bundles directory
    BUNDLES_DIR.mkdir(parents=True, exist_ok=True)
    
    # Bundle JavaScript
    print('Bundling JavaScript files...')
    js_bundle_path = BUNDLES_DIR / 'common.js'
    bundle_files(COMMON_JS_FILES, JS_DIR, js_bundle_path, minify_js)
    
    # Bundle CSS
    print('\nBundling CSS files...')
    css_bundle_path = BUNDLES_DIR / 'common.css'
    bundle_files(COMMON_CSS_FILES, CSS_DIR, css_bundle_path, minify_css)
    
    print('\nBundling complete!')
    print(f'\nBundles created in: {BUNDLES_DIR.relative_to(BASE_DIR)}')
    print(f'   - common.js (use in production)')
    print(f'   - common.css (use in production)')
    print('\nTo use bundles, replace individual script/style tags with:')
    print('   <script src="assets/bundles/common.js"></script>')
    print('   <link rel="stylesheet" href="assets/bundles/common.css">')

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\n\nBundling cancelled by user')
        sys.exit(1)
    except Exception as e:
        print(f'\nError during bundling: {e}')
        import traceback
        traceback.print_exc()
        sys.exit(1)

